### ISSUE TITLE
jpm xpi recursively packs the complete current directory into the xpi

### ISSUE THREAD

**Issue by rgh36167** [mozilla-jetpack/jpm#355] opened 2015-10-16 22:28 UTC
"cfx xpi" in the same directory works as expected.

This is pretty nasty as people might have private keys or similar stored here.

**Comment by autonome** [comment] 2015-10-28 08:49
It pulls in any XPI in the current directory, which causes errors on AMO when submitting:

https://i.imgur.com/Nq6mafx.png

**Comment by Noitidart** [comment] 2016-02-28 19:14
@rgh36167 I don't understand the issue with your statement, can you please explain what you expect the fix should be?

@autonome The fix for this would be to exclude all `.xpi` correct?

**Comment by sblask** [comment] 2016-02-28 20:38
This is why I had to do explicitly include by using `.jpmignore`: https://github.com/sblask/firefox-bookmark-dial/blob/master/.jpmignore Not great, but works. Found the solution in another bug, so I think this is a duplicate.

**Comment by Noitidart** [comment] 2016-02-28 20:53
Thanks for sharing that @sblask that is really useful! Having develoeprs create a .jpmignore (let alone learn the syntax for .jpmignore [if they arent familiar with .gitignore]) is a hassle.

**Comment by rgh36167** [comment] 2016-02-28 21:19
@Noitidart :  cfx somehow magically  included exactly the wanted files whereas jpm seems to include everything it can find (which also triggers the silly whitespace in filename bug whose issue# I have forgotten). This is not documented so it may cause some bad surprises.

**Comment by kumar303** [comment] 2016-02-29 15:30
I don't understand what the bug is. The cfx style of add-ons were drastically different from SDK-based add-ons. This is from jpm's [xpi docs](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_xpi):

> It ignores any ZIPs or XPIs in the add-on's root, and any test files. It includes all other files. If you want to exclude extra files, see the .jpmignore file.

That's pretty clear to me.

I'm also unsure how we would fix the bug as reported. Do you want to add more default ignore rules? In the meantime, I'm closing this until there is a better rationale for why this is a bug. Thanks for taking the time to report it.

**Closed by kumar303** 2016-02-29 15:30 UTC

**Comment by rgh36167** [comment] 2016-03-01 12:39
@kumar303:

the version which I installed on Feb 28th (says v1.0.6) does still include all *.xpi files found in the root directory.

The fact that .jpmignore needs to be used should be mentioned in
  https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx_to_jpm

**Comment by sblask** [comment] 2016-03-01 15:02
@rgh36167 I just checked, can't reproduce the issue with JPM 1.0.6 But I did find the original problem I had that brought me to `.jpmignore`. Really everything is included in the xpi, even `.git` folders, so I got a 25M instead of 300K file without my `.jpmignore`

**Comment by kumar303** [comment] 2016-03-01 16:39
> The fact that .jpmignore needs to be used should be mentioned in https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx_to_jpm

It is a wiki, please add anything to the docs that would have helped you when first reading it.

**Comment by kumar303** [comment] 2016-03-01 22:56
> jpm definitely packs .xpi and test/ on my system

Are you already defining a `.jpmignore` file? If so, that will take precedence over the defaults. The default rules are not merged with jpmignore rules.

> I would edit the wiki but whenever I try to login it says "Profile Creation Disabled".

It looks like this was fixed recently: https://bugzilla.mozilla.org/show_bug.cgi?id=1250360 Maybe it hasn't been deployed yet. You could ask in the bug.

**Comment by rgh36167** [comment] 2016-03-02 12:01
after moving .jpmignore out of the way it still does pack *.xpi but not test/*.  Anyway if .jpmignore is the way to go then this could be removed altogether in favor of example .jpmignore files.

The wiki problem is tracked but no idea when it will be fixed.

**Comment by Noitidart** [comment] 2016-03-06 09:08
Is what this dev went though  here - http://stackoverflow.com/a/35744547/1828637 - similar to what you are talking about @rgh36167?

**Comment by rgh36167** [comment] 2016-03-06 18:52
@Notidiart: seems like the same bug. Maybe it is somehow OS dependant - I am on Linux. Does it work on your system?

Also it seems many people don't realize they must use .jpmignore and I can't change the docs as long as the wiki account creation doesn't work:(

Maybe 'jpm init' could create an example .jpmignore to cover most cases?

**Comment by sblask** [comment] 2016-03-06 20:35
This is the same problem I had, but not anymore and I am on Linux too. So I think it was like this for me: jpm packed all the git files, I added a `.jpmignore` to ignore `.git` but did not have a rule for `*.xpi` so it was packed as well. Then I switched to explicit includes and everything worked fine...

Btw, IGNORE_FILES_REGEX seems to only be used in the watch command, not `jpm xpi`.

**Comment by learningloop** [comment] 2016-03-08 09:14
Hi @Noitidart Thank you for pointing me to this thread. Yes, as mentioned in the [stackoverflow question](http://stackoverflow.com/questions/35742449/exponential-increase-in-xpi-file-size-in-firefox-addon-development-for-each-buil) the exponential increase is observed with `jpm sign` in windows. I was developing the add-on based on the instructions mentioned here(https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_%28jpm%29). But, there is no mention of `.jpmignore`.
