### ISSUE TITLE
jpm sign: save downloaded files to a custom directory

### ISSUE THREAD

**Issue by tofutim** [mozilla-jetpack/jpm#551] opened 2016-07-13 07:50 UTC
Hi, is it possible to re-direct the output for jpm sign to a different directory? (in my case a 'bin' directory). I know I can change to that directory first...

**Comment by yan12125** [comment] 2016-07-13 09:29
It's not implemented yet. sign-addon has a ```downloadDir``` option while jpm does not use it.

**Comment by kumar303** [comment] 2016-07-13 22:06
It should be pretty easy to add now that we're using [sign-addon](https://github.com/mozilla/sign-addon/), I can mentor and review a patch for this.

**Comment by kumar303** [comment] 2016-10-11 20:41
If someone has a chance to work on this, I'd suggest trying to leverage the new `--dest-dir` option added to the `xpi` command in https://github.com/mozilla-jetpack/jpm/commit/8059d868f247ead03e8bd848f4e9cc79466e42d7

**Comment by kumar303** [comment] 2016-10-11 20:44
oops, this is a dupe of https://github.com/mozilla-jetpack/jpm/issues/371 which was filed first (I think)

**Closed by kumar303** 2016-10-11 20:44 UTC
