### ISSUE TITLE
Urgent for jpm sign to support proxy

### ISSUE THREAD

**Issue by vidyavijayabhanu** [mozilla-jetpack/jpm#603] opened 2016-12-20 05:10 UTC
Is jpm sign command currently supporting running it through a proxy server(specifying proxy ip as argument)?
If so since which version?
Please reply with link to jpm binaries that support proxy server if code changes have been made

**Comment by yan12125** [comment] 2016-12-20 05:14
It's not merged yet: #593

**Comment by vidyavijayabhanu** [comment] 2016-12-20 05:28
Hi

Any idea when will this get merged.
I am automating the process of signing my addon through jpm sign command
programmatically and this need to support running via proxy.

Regards
Vidya.V

**Comment by yan12125** [comment] 2016-12-20 05:44
Until the author of that PR or someone else fixes all the problems.

**Comment by kumar303** [comment] 2016-12-20 15:13
Hi @vidyavijayabhanu, thanks for taking the time to file an issue. I nudged the contributor on https://github.com/mozilla-jetpack/jpm/pull/593 to see if they can help finish out the patch. You could also start the same patch in a new pull request and make the requested changes if you'd like to get it released sooner.

I'm closing this issue since it's a duplicate of https://github.com/mozilla-jetpack/jpm/issues/446

If you have an urgent need to use a proxy, you can write a small script with [sign-addon](https://github.com/mozilla/sign-addon/) which has documentation on how to do so. Let me know if you get stuck.

**Closed by kumar303** 2016-12-20 15:13 UTC

**Comment by vidyavijayabhanu** [comment] 2016-12-21 05:04
Hi

I have written the script for using sign-addon and it works.
But the issue is we need nodejs to be installed in the system for running
the script.
In case of jpm sign I didnt face this issue.
I installed nodejs along with jpm sign node module and then copied all the
binaries to a system.
Now when I run jpm sign command from the path where it is copied it worked.
But in this case the script needs nodejs to be installed.
Please let me know if there is any alternative for the same like I want the
script to be run simply in the path where nodejs is present without
installing nodejs.
Let me know if my doubt is clear.

Regards
Vidya.V

**Comment by yan12125** [comment] 2016-12-21 05:13
Use shebangs?

**Comment by vidyavijayabhanu** [comment] 2016-12-21 05:15
I dont get you.

**Comment by yan12125** [comment] 2016-12-21 05:28
In your script:
```
#!/usr/bin/env node
(...javascript codes...)
```
And then ```chmod +x your_script```, then you can use ```./your_script```

**Comment by kumar303** [comment] 2016-12-21 05:57
Alternatively, you could distribute your script as an executable Node package using the `bin` key: https://docs.npmjs.com/files/package.json#bin This is why jpm "just worked," it defines itself as an executable: https://github.com/mozilla-jetpack/jpm/blob/master/package.json#L6

**Comment by vidyavijayabhanu** [comment] 2016-12-21 06:03
Ok I will try that.
Sounds good

**Comment by vidyavijayabhanu** [comment] 2016-12-23 12:30
Hi

I have packaged it as an executable.
But still it is not working without installing nodejs

Regards
Vidya.V

**Comment by kumar303** [comment] 2016-12-23 15:55
Hi. Since this repo is specifically about JPM, it's not the best place to get general NodeJS help. You will probably find answers faster by searching the web. A quick search to your question shows some answers like http://stackoverflow.com/questions/14314038/how-do-i-deploy-node-js-applications-as-a-single-executable-file

**Comment by vidyavijayabhanu** [comment] 2017-03-07 10:40
Hi

This is based on https://github.com/mozilla-jetpack/jpm/issues/446

Will the apiproxy added in jpm 1.3.0 support running it through a proxy
machine prompting for user name and password?

Regards
Vidya.V
