### ISSUE TITLE
Incorrect authentication credentials

### ISSUE THREAD

**Issue by uri-wisestamp** [mozilla-jetpack/jpm#469] opened 2016-01-25 10:38 UTC
headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
JPM [debug] [API] <- { headers:
   { allow: 'GET, PUT, HEAD, OPTIONS',
     'content-type': 'application/json',
     date: 'Mon, 25 Jan 2016 10:37:05 GMT',
     server: 'nginx',
     'set-cookie': '<REDACTED>',
     'strict-transport-security': 'max-age=31536000',
     vary: 'Accept, X-Mobile, User-Agent',
     'www-authenticate': 'JWT realm="api"',
     'x-frame-options': 'DENY',
     'content-length': '51',
     connection: 'Close' },
  response: { detail: 'Incorrect authentication credentials.' } }
JPM [error] FAIL
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.8.20.14/

status: 401
response: {"detail":"Incorrect authentication credentials."}
headers: {"allow":"GET, PUT, HEAD, OPTIONS","content-type":"application/json","date":"Mon, 25 Jan 2016 10:37:05 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Mon, 25-Jan-2016 10:37:20 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Accept, X-Mobile, User-Agent","www-authenticate":"JWT realm=\"api\"","x-frame-options":"DENY","content-length":"51","connection":"Close"}

    at C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\lib\amo-client.js:85:13
    at tryCatchReject (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\Scheduler.js:27:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

I checked and our credentials are correct.

**Comment by Noitidart** [comment] 2016-01-25 14:12
I'm blindly guessing this is a timing issue, please try syncing your clock to NTP and trying again.

Related issues I think:

* https://github.com/mozilla/olympia/issues/1071
* https://github.com/mozilla/olympia/issues/1109
* https://github.com/mozilla/olympia/issues/1369#issuecomment-171858421

**Comment by kumar303** [comment] 2016-01-25 19:49
Once the fix for https://github.com/mozilla/olympia/issues/1071 lands, you should see an exact error message if your clock is off.

**Comment by uri-wisestamp** [comment] 2016-01-26 07:31
After taking my clock one minute back, it worked. However this should work also with the clock adjusted.

**Comment by kumar303** [comment] 2016-01-26 17:34
> After taking my clock one minute back

You mean setting it back manually? Did you try using NTP or anything to synchronize it? You shouldn't have to set it manually and that would be more error prone actually.

**Comment by kumar303** [comment] 2016-01-26 17:34
Information on NTP: http://www.ntp.org/

**Comment by uri-wisestamp** [comment] 2016-01-27 06:57
Yes, I set it one minute back manually.

**Comment by kumar303** [comment] 2016-03-31 15:00
At this time, API authentication requires that you have a synchronized clock. Since that seems like the cause of the failure, it is expected so I'm closing the issue. Thanks for the report!

**Closed by kumar303** 2016-03-31 15:00 UTC
