### ISSUE TITLE
npm install jpm --global

### ISSUE THREAD

**Issue by david141** [mozilla-jetpack/jpm#493] opened 2016-02-13 18:55 UTC
Error in nodejs can anyone aware of what's the harm?
After the command **npm install jpm --global** ERROR.

**npm-debug.log**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'jpm',
1 verbose cli   '--global' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose stack Error: Failed to replace env in config: ${APPDATA}
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:417:13
4 verbose stack     at String.replace (native)
4 verbose stack     at envReplace (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:413:12)
4 verbose stack     at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:391:7)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:334:17
4 verbose stack     at Array.forEach (native)
4 verbose stack     at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:333:23)
4 verbose stack     at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
4 verbose stack     at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
5 verbose cwd C:\Program Files\nodejs
6 error Windows_NT 6.1.7600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "jpm" "--global"
8 error node v5.6.0
9 error npm  v3.6.0
10 error Failed to replace env in config: ${APPDATA}
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by kumar303** [comment] 2016-02-13 21:55
This is a duplicate of https://github.com/mozilla-jetpack/jpm/issues/494 I added some information to help you solve it.

**Closed by kumar303** 2016-02-13 21:55 UTC
